ProyectoEncuestas/ProyectoEncuestas/Models/encuestas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEncuestas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuestas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public encuestas()
        {
            this.preguntas = new HashSet<preguntas>();
            this.respuestas = new HashSet<respuestas>();
        }
    
        public int id { get; set; }
        public int categoria_id { get; set; }
        public string nombre { get; set; }
        public byte status_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preguntas> preguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuestas> respuestas { get; set; }
    }
}

ProyectoEncuestas/ProyectoEncuestas/Controllers/Api/EncuestasController.cs
using ProyectoEncuestas.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace ProyectoEncuestas.Controllers.Api
{
    public class EncuestasController : ApiController
    {

        // GET: /Encuesta/Activas/{ID Categoria (opcional)}
        // Muestra las encuestas activas filtradas por categoría
        // Solo los administradores y encuestados tienen acceso
        public List<EncuestasCE> GetIndex(string id = "")
        {
            List<EncuestasCE> data = new List<EncuestasCE>();
            try
            {
                /*
                 * Cargarmos el context que nos permitira conectar con la base de datos
                 * Ejecutamos un query en la base de datos, tratando los parametros para impedir sql injection
                 * Finalmente regresamos el resultado
                 */
                using (iainteractiveEntities db = new iainteractiveEntities())
                {
                    string queryString = @"select distinct a.id,a.nombre,a.categoria_id, a.status_id,a.created_at,b.categoria as categoria_name,c.status as status_name
                        from encuestas as a 
                        inner join categorias b on a.categoria_id = b.id
                        inner join status c on a.status_id = c.id
                        where a.status_id = 1" + (id !="" ? " and b.categoria = @cat " : "") + @"
                        order by b.categoria, a.nombre";

                     data = db.Database.SqlQuery<EncuestasCE>(queryString, new SqlParameter("cat ", id)).ToList();
                    return data;
                }

            }
            catch (Exception )
            {
                return data;
            }
           
        }
    }
}

ProyectoEncuestas/ProyectoEncuestas/Controllers/EncuestaController.cs
using Microsoft.AspNet.Identity;
using ProyectoEncuestas.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoEncuestas.Controllers
{
    public class EncuestaController : Controller
    {
        // GET: /Encuesta/Admin  
        // Muestra la lista de encuestas
        // Solo los Administradores tienen acceso
        [Authorize(Roles = "Administrador")]
        public ActionResult Admin()
        {
            try
            {
                /*
                 * Cargarmos el context que nos permitira conectar con la base de datos
                 * Mediante LinQ obtenemos las encuestas con sus estatus y categorias, y los retornamos a la vista en forma de lista
                 */
                using (iainteractiveEntities db = new iainteractiveEntities())
                {
                    var data = from a in db.encuestas
                               join b in db.categorias on a.categoria_id equals b.id
                               join c in db.status on a.status_id equals c.id
                               select new EncuestasCE()
                               {
                                   id = a.id,
                                   nombre = a.nombre,
                                   categoria_id = a.categoria_id,
                                   status_id = a.status_id,
                                   created_at = a.created_at,
                                   categoria_name = b.categoria,
                                   status_name = c.status1
                               };


                    return View(data.ToList());
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al cargar la lista de encuestas " + ex.Message);
                return View();
            }
        }

        // GET: /Encuesta/Create
        // Muestra la vista para crear encuestas
        // Solo los Administradores tienen acceso
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            // simplemente llamamos la vista que nos permitira crear una encuesta
            return View();
        }

        // POST Encuesta/Create
        // Crea una encuesta
        // Solo los Administradores tienen acceso
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Create(encuestas data)
        {
            // Validamos que los parametros se recibieron (es una validación simple que por tiempo es lo que pudimos hacer )
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            try
            {
                /*
                 * Cargarmos el context que nos permitira conectar con la base de datos
                 * Como no recibimos la fecha de creación desde la vista aquí es donde la establecemos con DateTime.Now
                 * En el contexto de "encuestas" cargamos los datos que recibimos por POST y guardamos los cambios, para finalmente redirigir a /Preguntas/Create
                 */
                using (iainteractiveEntities db = new iainteractiveEntities())
                {
                    data.created_at = DateTime.Now;
                    db.encuestas.Add(data);
                    db.SaveChanges();

                    return RedirectToAction("Create", "Preguntas", new { id = data.id });
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al agregar la categoría " + ex.Message);
                return RedirectToAction("Admin");
            }
        }

        // GET: /Encuesta/Edit/{ID}
        // Muestra la vista para editar las encuestas
        // Solo los administradores tienen acceso
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int id = 0)
        {
            // Validamos que los parametros se recibieron (es una validación simple que por tiempo es lo que pudimos hacer )
            // validamos tambien que el id de la encuesta sea mayor que cero
            if (!ModelState.IsValid || id < 1)
            {
                return RedirectToAction("Admin");
            }
            try
            {
                /*
                 * Cargarmos el context que nos permitira conectar con la base de datos
                 * Buscamos la encuesta mediante el id que recibimos por GET y enviamos los resultados a la vista para que sean mostrados
                 */
                using (iainteractiveEntities db = new iainteractiveEntities())
                {
                    var encuesta = db.encuestas.Find(id);
                    return View(encuesta);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al mostrar la encuesta para edición" + ex.Message);
                return RedirectToAction("Admin");
            }
        }

        // POST: /Encuesta/Edit
        // Actualiza la información de una encuesta
        // Solo los administradores tienen acceso
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(encuestas data)
        {
            // Validamos que los parametros se recibieron (es una validación simple que por tiempo es lo que pudimos hacer )
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Admin");
            }
            try
            {
                /*
                 * Cargarmos el context que nos permitira conectar con la base de datos
                 * Buscamos la encuesta mediante el id, posteriomente modificamos los campos necesarios en el modelo para poder guardar la información en la base de datos
                 * Finalmente redirigmos a /Encuesta/Admin
                 */
                using (iainteractiveEntities db = new iainteractiveEntities())
                {
                    encuestas encuesta = db.encuestas.Find(data.id);
                    encuesta.nombre = data.nombre;
                    encuesta.categoria_id = data.categoria_id;
                    encuesta.status_id = data.status_id;
                    //   encuesta.created_at = data.created_at;
                    db.SaveChanges();

                    return RedirectToAction("Admin");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al editar la encuesta " + ex.Message);
                return View();
            }
        }

        // GET: /Encuesta/Edit/{ID}
        // Elimina Fisicamente una encuesta
        // Solo los administradores tienen acceso
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int id = 0)
        {
            // Validamos que los parametros se recibieron (es una validación simple que por tiempo es lo que pudimos hacer )
            if (!ModelState.IsValid || id < 1)
            {
                return RedirectToAction("Admin");
            }
            try
            {
                /*
                 * Cargarmos el context que nos permitira conectar con la base de datos
                 * Buscamos la encuesta mediante el id que recibimos por GET, despues indicamos que encuesta de nuestro contexto db va a ser eliminado
                 * Finalmente guardamos los cambios y redirigimos a /Encuesta/Admin
                 */
                using (iainteractiveEntities db = new iainteractiveEntities())
                {
                    var categoria = db.encuestas.Find(id);
                    db.encuestas.Remove(categoria);
                    db.SaveChanges();

                    return RedirectToAction("Admin");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al eliminar la categoría " + ex.Message);
                return View();
            }
        }

        // GET: /Encuesta/Details/{ID}
        // Muestra el detalle de una encuesta
        // Solo los administradores tienen acceso
        [Authorize(Roles = "Administrador")]
        public ActionResult Details(int id = 0)
        {
            // Validamos que los parametros se recibieron (es una validación simple que por tiempo es lo que pudimos hacer )
            if (!ModelState.IsValid || id < 1)
            {
                return RedirectToAction("Admin");
            }
            try
            {
                /*
                 * Cargarmos el context que nos permitira conectar con la base de datos
                 * buscamos la encuesta que coincida con el id que recibimos por GET
                 * Establecemos la información en el modelo EncuestasCE y finalmente enviamos la información a la vsita
                 */
                using (iainteractiveEntities db = new iainteractiveEntities())
                {
                    var data = from a in db.encuestas
                               join b in db.categorias on a.categoria_id equals b.id
                               join c in db.status on a.status_id equals c.id
                               where a.id == id
                               select new EncuestasCE()
                               {
                                   id = a.id,
                                   nombre = a.nombre,
                                   categoria_id = a.categoria_id,
                                   status_id = a.status_id,
                                   created_at = a.created_at,
                                   categoria_name = b.categoria,
                                   status_name = c.status1
                               };

ProyectoEncuestas/ProyectoEncuestas/Controllers/StatusController.cs
using ProyectoEncuestas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoEncuestas.Controllers
{
    public class StatusController : Controller
    {
        // GET: /Status
        // Es una vista parcial que muestra un combobox con la lista de estatus disponibles
        public ActionResult cmbStatus(int id = 1)
        {
            try
            {
                /*
                 * Cargarmos el context que nos permitira conectar con la base de datos
                 * Obtiene la lista de estatus y envia el resultado a la vista
                 */
                ViewBag.statusId = id;
                using (iainteractiveEntities db = new iainteractiveEntities())
                {
                    List<status> listStatus = db.status.ToList();
                    return PartialView(listStatus );
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al Mostrar la lista de estatus " + ex.Message);
                return PartialView(null);
            }
        }
    }
}

ProyectoEncuestas/ProyectoEncuestas/Views/Encuesta/Activas.cshtml
@model IEnumerable<ProyectoEncuestas.Models.EncuestasCE>

@{
    ViewBag.Title = "Encuestas Activas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th colspan="3">
           
        </th>
        <th>
            @Html.Action("cmbCategorias_WithSelect", "Categoria", new { id = ViewBag.categoria_id })
        </th>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.categoria_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.created_at)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.categoria_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        
        <td>
            @item.created_at.ToShortDateString()
        </td>
        <td>
            @Html.ActionLink("Responder", "FormAnswer", new { id=item.id }) 
        </td>
    </tr>
}

</table>

@section Scripts{
    <script type="text/javascript">
        $('#categoria_id').change(function (event) {
            
            document.location.href = "/Encuesta/Activas/" + $(this).val();
        });
    </script>    
}

ProyectoEncuestas/ProyectoEncuestas/Views/Encuesta/Admin.cshtml
@model IEnumerable<ProyectoEncuestas.Models.EncuestasCE>

@{
    ViewBag.Title = "Administración de Encuestas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Nueva Encuesta", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.categoria_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.created_at)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.categoria_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status_name)
        </td>
        <td>
            @item.created_at.ToShortDateString()
        </td>
        <td>
            
            @Html.ActionLink("Editar Preguntas", "Index", "Preguntas", new { id = item.id }, "id"  ) |
            @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.id }, new { @class = "lnkDelete" } )
        </td>
    </tr>
}

</table>
@section scripts{
    <script type="text/javascript">
        $('.lnkDelete').click(function (event) {
            var encuesta = $(this).parent().parent().children('td:nth-child(2)').text();
            if (!confirm("¿Esta usted seguro de eliminar esta encuesta: '" + encuesta.trim() + "' ?")) {
                event.preventDefault();
            }
        });
    </script>    
    
}

ProyectoEncuestas/ProyectoEncuestas/Views/Encuesta/Create.cshtml
@model ProyectoEncuestas.Models.encuestas

@{
    ViewBag.Title = "Nueva Encuesta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.categoria_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.Action("cmbCategorias", "Categoria", new { id = 0 })
                @Html.ValidationMessageFor(model => model.categoria_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("cmbStatus", "Status", new { id = 1 })                
                @Html.ValidationMessageFor(model => model.status_id, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Admin")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoEncuestas/ProyectoEncuestas/Views/Encuesta/Details.cshtml
@model ProyectoEncuestas.Models.EncuestasCE

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalle de la encuesta: @Model.nombre</h2>

<div>
    
    <p>
        @Html.ActionLink("Regresar", "Admin")
    </p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.categoria_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_at)
        </dt>

        <dd>
            @Model.created_at.ToShortDateString()
        </dd>

    </dl>
</div>


@Html.Action("IndexPartial", "Preguntas", new { id = Model.id })

ProyectoEncuestas/ProyectoEncuestas/Views/Encuesta/Edit.cshtml
@model ProyectoEncuestas.Models.encuestas

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar la encuesta: @Model.nombre </h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.categoria_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("cmbCategorias", "Categoria", new { id = Model.categoria_id })
                @Html.ValidationMessageFor(model => model.categoria_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("cmbStatus", "Status", new { id = Model.status_id })
                @Html.ValidationMessageFor(model => model.status_id, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Admin")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoEncuestas/ProyectoEncuestas/Views/Encuesta/FormAnswer.cshtml
@model ProyectoEncuestas.Models.EncuestasCE

@{
    ViewBag.Title = "Encuesta @Model.nombre";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Responde la encuesta</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
       
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

      

        <dt>
            @Html.DisplayNameFor(model => model.created_at)
        </dt>

        <dd>
            @Model.created_at.ToShortDateString()
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status_name)
        </dd>

    </dl>
</div>
@Html.Action("FormPartialAnswers", "Preguntas", new { id = Model.id })

<p>
    
    @Html.ActionLink("Regresar", "Activas","Encuesta")
</p>

ProyectoEncuestas/ProyectoEncuestas/Views/Encuesta/MyAnswers.cshtml
@model IEnumerable<ProyectoEncuestas.Models.EncuestasCE>

@{
    ViewBag.Title = "MyAnswers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mis Encuestas</h2>

<table class="table">
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.categoria_name)
        </th>
        
        
        <th>
            @Html.DisplayNameFor(model => model.created_at)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.status_name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.categoria_name)
        </td>
        <td>
            @item.created_at.ToShortDateString()
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status_name)
        </td>
    </tr>
}

</table>